language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - graphviz
      - thrift
install: "mvn --show-version --errors --batch-mode validate dependency:go-offline"
script: "mvn --show-version --errors --batch-mode clean install -Dmaven.test.skip=true"
cache:
    directories:
    - $HOME/.m2
notifications:
    email:
        - cpp8238065@163.com
